# Generated by Django 6.0.6 on 2026-06-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100, verbose_name='Имя гостя')),
                ('song_title', models.CharField(blank=True, max_length=200, verbose_name='Название трека')),
                ('artist', models.CharField(blank=True, max_length=200, verbose_name='Исполнитель')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('moment', models.CharField(blank=True, choices=[('dinner', 'Фон на банкете'), ('dance', 'Танцы'), ('slow', 'Медляк'), ('wishlist', 'Просто хочу услышать')], max_length=20, verbose_name='Когда включить')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'заявка на трек',
                'verbose_name_plural': 'заявки на треки',
                'ordering': ['-created_at'],
            },
        ),
    ]
