# Generated by Django 6.0.6 on 2026-07-16 06:57

from datetime import datetime
from zoneinfo import ZoneInfo

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_wedding_page(apps, schema_editor):
    WeddingPage = apps.get_model("songs", "WeddingPage")
    WeddingEvent = apps.get_model("songs", "WeddingEvent")
    WeddingFAQ = apps.get_model("songs", "WeddingFAQ")
    WeddingInfoBlock = apps.get_model("songs", "WeddingInfoBlock")

    tz = ZoneInfo("Europe/Moscow")
    page = WeddingPage.objects.create(
        groom_name="Алексей",
        bride_name="Мария",
        wedding_date=datetime(2026, 9, 4, 11, 45, tzinfo=tz),
        timezone_name="Europe/Moscow",
        hero_kicker="4 сентября 2026",
        invitation_text=(
            "В нашей жизни скоро состоится важное событие - наша свадьба! "
            "Мы приглашаем вас и будем рады провести этот особенный день "
            "в кругу самых близких людей!"
        ),
        location_title="Место проведения",
        location_name="Мономах",
        location_address="Мономах, Владимир, улица Гоголя, 20",
        location_map_url="https://yandex.ru/maps/-/CTUQy69U",
        footer_title="Будем счастливы видеть вас!",
        footer_text="Спасибо, что разделите с нами этот день.",
    )

    events = [
        ("Сбор гостей", "ул. Растопчина 51", 11, 20),
        ("Церемония регистрации", "ул. Растопчина 51", 11, 45),
        ("Фуршет", "улица Гоголя, 20", 12, 30),
        ("Фотосет Жениха и Невесты", "центр города", 12, 30),
        ("Праздничный банкет", "улица Гоголя, 20", 14, 0),
        ("Завершение вечера", "", 20, 0),
    ]
    for order, (title, description, hour, minute) in enumerate(events, start=1):
        WeddingEvent.objects.create(
            page=page,
            title=title,
            description=description,
            starts_at=datetime(2026, 9, 4, hour, minute, tzinfo=tz),
            order=order,
        )

    info_blocks = [
        (
            "Регистрация",
            "На торжественную регистрацию брака могут поехать все желающие.",
            "",
            "",
        ),
        (
            "Трансфер",
            "Трансфер будет организован от гостиницы Мономах.",
            "",
            "",
        ),
        (
            "Второй день",
            (
                "Второй день планируется на тур-базе Ладога: беседка, шашлык, "
                "спортивные и настольные активности. Есть домики под съем для желающих."
            ),
            "Тур-база Ладога",
            "https://ladogapark33.ru/",
        ),
    ]
    for order, (title, body, link_label, link_url) in enumerate(info_blocks, start=1):
        WeddingInfoBlock.objects.create(
            page=page,
            title=title,
            body=body,
            link_label=link_label,
            link_url=link_url,
            order=order,
        )

    faqs = [
        (
            "Где ночевать гостям не из Владимира?",
            "Банкет проходит в Ресторане при гостинице Мономах, можно забронировать номера заранее.",
        ),
        (
            "На регистрацию брака можно поехать?",
            "Да, на торжественную регистрацию брака могут поехать все желающие.",
        ),
        (
            "Будет ли второй день?",
            (
                "Второй день планируется на тур-базе Ладога, снимем беседку, шашлык, "
                "спортивные и настольные активности. Есть домики под съем для желающих."
            ),
        ),
        (
            "Как найти тур-базу Ладога?",
            "Адрес: https://yandex.ru/maps/-/CTUQy69U\nСайт: https://ladogapark33.ru/",
        ),
        (
            "Можно ли добавить музыку для банкета?",
            "Да, для этого сделали специальную форму для добавления желаемой музыки: http://alexey-maria.ru/",
        ),
        (
            "Будет ли организован трансфер до места проведения свадьбы?",
            "Трансфер будет организован от гостиницы Мономах.",
        ),
        (
            "Будет ли свадьба проходить на открытом воздухе? Нужно ли что-то взять с собой?",
            "Фуршет планируется на веранде ресторана, если будет хорошая погода. Сам банкет в большом зале.",
        ),
        (
            "Есть ли Telegram-чат или канал с актуальной информацией по свадьбе?",
            "Информация с актуальной информацией будет на: http://alexey-maria.ru/",
        ),
    ]
    for order, (question, answer) in enumerate(faqs, start=1):
        WeddingFAQ.objects.create(
            page=page,
            question=question,
            answer=answer,
            order=order,
        )


def remove_seed_wedding_page(apps, schema_editor):
    WeddingPage = apps.get_model("songs", "WeddingPage")
    WeddingPage.objects.filter(groom_name="Алексей", bride_name="Мария").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120, verbose_name='Имя гостя')),
                ('attendance', models.CharField(choices=[('yes', 'Приду'), ('no', 'Не смогу'), ('maybe', 'Уточню позже')], max_length=12, verbose_name='Придет ли гость')),
                ('guests_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество гостей')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'ответ гостя',
                'verbose_name_plural': 'ответы гостей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeddingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(default='Алексей', max_length=80, verbose_name='Имя жениха')),
                ('bride_name', models.CharField(default='Мария', max_length=80, verbose_name='Имя невесты')),
                ('wedding_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время свадьбы')),
                ('timezone_name', models.CharField(default='Europe/Moscow', max_length=64, verbose_name='Часовой пояс')),
                ('hero_kicker', models.CharField(default='Свадебное приглашение', max_length=160, verbose_name='Надпись над заголовком')),
                ('invitation_text', models.TextField(default='В нашей жизни скоро состоится важное событие - наша свадьба! Мы приглашаем вас и будем рады провести этот особенный день в кругу самых близких людей!', verbose_name='Текст приглашения')),
                ('location_title', models.CharField(default='Место проведения', max_length=160, verbose_name='Заголовок места')),
                ('location_name', models.CharField(default='Мономах', max_length=180, verbose_name='Название площадки')),
                ('location_address', models.CharField(default='Мономах, Владимир, улица Гоголя, 20', max_length=300, verbose_name='Адрес')),
                ('location_map_url', models.URLField(blank=True, default='https://yandex.ru/maps/-/CTUQy69U', verbose_name='Ссылка на карту')),
                ('footer_title', models.CharField(default='Будем счастливы видеть вас!', max_length=180, verbose_name='Финальный заголовок')),
                ('footer_text', models.TextField(blank=True, default='Спасибо, что разделите с нами этот день.', verbose_name='Финальный текст')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'страница свадьбы',
                'verbose_name_plural': 'страница свадьбы',
            },
        ),
        migrations.CreateModel(
            name='WeddingInfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('link_label', models.CharField(blank=True, max_length=120, verbose_name='Текст ссылки')),
                ('link_url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_blocks', to='songs.weddingpage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'информационный блок',
                'verbose_name_plural': 'информационные блоки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeddingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='songs.weddingpage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'вопрос и ответ',
                'verbose_name_plural': 'вопросы и ответы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeddingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание/адрес')),
                ('starts_at', models.DateTimeField(verbose_name='Время')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='songs.weddingpage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'событие программы',
                'verbose_name_plural': 'программа свадьбы',
                'ordering': ['order', 'starts_at', 'id'],
            },
        ),
        migrations.RunPython(seed_wedding_page, remove_seed_wedding_page),
    ]
