# Generated by Django 6.0.6 on 2026-07-16 07:36

from django.db import migrations, models


def seed_announcement(apps, schema_editor):
    ImportantAnnouncement = apps.get_model("songs", "ImportantAnnouncement")
    ImportantAnnouncement.objects.create(
        title="Важная информация",
        body="Здесь можно написать важное сообщение для гостей.",
        is_active=False,
        show_to_guests=False,
        archived=False,
    )


def remove_seed_announcement(apps, schema_editor):
    ImportantAnnouncement = apps.get_model("songs", "ImportantAnnouncement")
    ImportantAnnouncement.objects.filter(
        title="Важная информация",
        body="Здесь можно написать важное сообщение для гостей.",
        view_count=0,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_guestrsvp_weddingpage_weddinginfoblock_weddingfaq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=64, unique=True, verbose_name='ID посетителя')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Первый визит')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последний визит')),
                ('visit_count', models.PositiveIntegerField(default=1, verbose_name='Визитов')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('last_path', models.CharField(blank=True, max_length=240, verbose_name='Последний путь')),
            ],
            options={
                'verbose_name': 'посетитель сайта',
                'verbose_name_plural': 'посетители сайта',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportantAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('show_to_guests', models.BooleanField(default=True, verbose_name='Показывать гостям')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'важная информация',
                'verbose_name_plural': 'важная информация',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.RunPython(seed_announcement, remove_seed_announcement),
    ]
