# Generated by Django 6.0.6 on 2026-07-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_refine_wedding_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingpage',
            name='footer_image',
            field=models.ImageField(blank=True, upload_to='wedding_page/', verbose_name='Нижнее фото'),
        ),
        migrations.AddField(
            model_name='weddingpage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='wedding_page/', verbose_name='Верхнее фото'),
        ),
    ]
